### ISSUE TITLE
Use more precise config constraint

### ISSUE THREAD

**Issue by NoahStallinger** [webbuilders-group/silverstripe-cmspreviewpreference#6]
The use of a wildcard in the config.yml's "After" setting can cause a circular dependency exception when used in silverstripe 5 with MAILER_DSN enabled.

```
Fatal error:  Uncaught MJS\TopSort\CircularDependencyException: Circular dependency found: modelascontrollercatchallroute->cmspreviewpreference->mailer-dsn-env->cmspreviewpreference in /vendor/marcj/topsort/src/CircularDependencyException.php:34
Stack trace:
#0 /vendor/marcj/topsort/src/Implementations/BaseImplementation.php(57): MJS\TopSort\CircularDependencyException::create()
#1 /vendor/marcj/topsort/src/Implementations/ArraySort.php(63): MJS\TopSort\Implementations\BaseImplementation->throwCircularExceptionIfNeeded()
#2 /vendor/marcj/topsort/src/Implementations/ArraySort.php(75): MJS\TopSort\Implementations\ArraySort->visit()
#3 /vendor/marcj/topsort/src/Implementations/ArraySort.php(75): MJS\TopSort\Implementations\ArraySort->visit()
#4 /vendor/marcj/topsort/src/Implementations/ArraySort.php(75): MJS\TopSort\Implementations\ArraySort->visit()
#5 /vendor/marcj/topsort/src/Implementations/ArraySort.php(115): MJS\TopSort\Implementations\ArraySort->visit()
#6 /vendor/marcj/topsort/src/Implementations/ArraySort.php(98): MJS\TopSort\Implementations\ArraySort->doSort()
#7 /vendor/silverstripe/config/src/Transformer/YamlTransformer.php(517): MJS\TopSort\Implementations\ArraySort->sort()
#8 /vendor/silverstripe/config/src/Transformer/YamlTransformer.php(104): SilverStripe\Config\Transformer\YamlTransformer->getSortedYamlDocuments()
#9 /vendor/silverstripe/config/src/Collections/MemoryConfigCollection.php(73): SilverStripe\Config\Transformer\YamlTransformer->transform()
#10 /vendor/silverstripe/framework/src/Core/Config/CoreConfigFactory.php(89): SilverStripe\Config\Collections\MemoryConfigCollection->transform()
#11 /vendor/silverstripe/framework/src/Core/Config/CoreConfigFactory.php(67): SilverStripe\Core\Config\CoreConfigFactory->createCore()
#12 [internal function]: SilverStripe\Core\Config\CoreConfigFactory->SilverStripe\Core\Config\{closure}()
#13 /vendor/silverstripe/config/src/Collections/CachedConfigCollection.php(139): call_user_func()
#14 /vendor/silverstripe/config/src/Collections/CachedConfigCollection.php(88): SilverStripe\Config\Collections\CachedConfigCollection->getCollection()
#15 /vendor/silverstripe/framework/src/Core/Config/Config_ForClass.php(81): SilverStripe\Config\Collections\CachedConfigCollection->get()
#16 /vendor/silverstripe/framework/src/Core/Config/Config_ForClass.php(114): SilverStripe\Core\Config\Config_ForClass->get()
#17 /vendor/silverstripe/framework/src/Core/Manifest/ModuleManifest.php(232): SilverStripe\Core\Config\Config_ForClass->uninherited()
#18 /vendor/silverstripe/framework/src/Core/BaseKernel.php(200): SilverStripe\Core\Manifest\ModuleManifest->sort()
#19 /vendor/silverstripe/framework/src/Core/CoreKernel.php(32): SilverStripe\Core\BaseKernel->bootManifests()
#20 /vendor/silverstripe/framework/src/Control/HTTPApplication.php(132): SilverStripe\Core\CoreKernel->boot()
#21 /vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(65): SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}()
#22 /vendor/silverstripe/framework/src/Control/HTTPApplication.php(130): SilverStripe\Control\HTTPApplication->callMiddleware()
#23 /vendor/silverstripe/framework/src/Control/HTTPApplication.php(113): SilverStripe\Control\HTTPApplication->execute()
#24 /public/index.php(24): SilverStripe\Control\HTTPApplication->handle()
#25 {main}
  thrown in /vendor/marcj/topsort/src/CircularDependencyException.php on line 34
```

**Comment by UndefinedOffset** [comment]
Can you give master a try and let me know if the issue is corrected for you now

**Comment by NoahStallinger** [comment]
Yes the issue does not occur anymore with dev-master version!

Thank you very much

**Comment by UndefinedOffset** [comment]
Tagged as 2.1.1
